// Code generated by 'go run tools/generate_errors/main.go  error/codes'. DO NOT EDIT.
package code

const (
	ECNULL                          = 0
	ErrParam                        = 1
	ErrUniqueKey                    = 2
	ErrAppTypeNoDefined             = 3
	ErrHelmChartAPIVersion          = 4
	ErrJobExecuting                 = 5
	ErrJobCantStop                  = 6
	ErrConfigNotComfirm             = 7
	ErrComponentUsing               = 8
	ErrApplicationFile              = 9
	ErrConfigValidate               = 10
	ErrNotFound                     = 11
	ErrHelmRepoNoFound              = 12
	ErrHelmChartNoFound             = 13
	ErrSystemNofound                = 14
	ErrComponentVersionLess         = 15
	ErrComponentNotFound            = 16
	ErrComponentDup                 = 17
	ErrAPPlicationComponentTortuous = 18
	ErrComponentTypeNotDefined      = 19
	ErrComponentInstanceRevission   = 20
	ErrComponentDecodeError         = 21
	ErrJobOwnerError                = 22
	ErrApplicationStillUse          = 23
	ErrHelmRepoUnknow               = 24
	ECTimeout                       = 25
	ECJobCancel                     = 26
	ECContextEnd                    = 27
	ECHelmChartNotFound             = 28
	ECHelmReleaseNotFound           = 29
	ECHelmReleaseForceUpdate        = 30
	ECHelmRun                       = 31
	ECHelmTimeout                   = 32
	ECHelmK8s                       = 33
	ECHelmK8SORRender               = 34
	ECTemplate                      = 35
	ECParseChart                    = 36
	ECExit                          = 37
	ECComponentDefined              = 38
	ECK8sUnknow                     = 39
	ECNetUnknow                     = 40
	ECSQLUnknow                     = 41
	ECHTTPAPIRawError               = 42
	ECBaseNode                      = 43
	ECNoAvailableWorker             = 44
	ECNoAuthorized                  = 45
	ECInvalidAuthorized             = 46
	ECColumnExists                  = 47
	ErrApplicationNotFound          = 48
	ECPriKeyExists                  = 49
)
