apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: class-443
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3000'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3000'

spec:
  rules:
  - http:
      paths:
      - path: /repository/api/v1
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 9527


