apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name  }}-dbconfig
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  config.yaml: |
    {{- range $key, $val := .Values.depServices.rds }}
      {{ $key }}: {{ $val | quote }}
    {{- end}}

