{{- if empty .Values.depServices.serviceAccountName  }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: {{ .Release.Name  }}
  namespace: {{ .Values.namespace }}
{{- end}}

---
{{- if empty .Values.depServices.serviceAccountName  }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name   }}
  labels:
    app: {{ .Release.Name  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
{{- end}}

---
{{- if empty .Values.depServices.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name  }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources:
    - "endpoints"
  verbs:
    - "get"
    - "watch"
    - "list"
{{- end}}