apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "component-manage.name" .}}-conf
  namespace: {{ template "component-manage.namespace" . }}
data:
  config.yaml: |
    log:
      level: debug
      format: json

    server:
      host: "0.0.0.0"
      port: 8888

    config:
      enableDualStack: {{ .Values.service.enableDualStack }}
      chartmuseum: {{ .Values.service.config.chartmuseum | toYaml | nindent 8 }}
      oci: {{ .Values.service.config.oci | toYaml | nindent 8 }}
      registry: {{ .Values.image.registry | quote }}

    persist:
      secret_components_name: persist-component-manage-components
      secret_plugins_name: persist-component-manage-plugins
      secret_namespace: {{ template "component-manage.namespace" . }}

