{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "component-manage.serviceAccountName" . }}
  namespace: {{ template "component-manage.namespace" . }}
  labels:
    {{- include "component-manage.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "component-manage.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "component-manage.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "component-manage.serviceAccountName" . }}
    namespace: {{ template "component-manage.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "component-manage.serviceAccountName" . }}
rules:
  - apiGroups:
      - "*"
    resources:
      - '*'
    verbs:
      - "*"
{{- end -}}