package file

import (
	"bytes"
)

const (
	ProtonCLIAutoGeneratedHeadFlag = "# The following is automatically generated by Proton CLI. Do not edit manually!\n"
	ProtonCLIAutoGeneratedTailFlag = "# End of content automatically generated by Proton CLI\n"
)

// 从指定 orig 中获取 head 和 tail 之间的内容
func GetManagedContent(orig, head, tail []byte) (cont []byte) {
	var _, h, t, _ = GetManagedIndexes(orig, head, tail)
	if h == t {
		return
	}
	cont = make([]byte, t-h)
	copy(cont, orig[h:t])
	return
}

// 修改 orig 中 head 和 tail 之间的部分未 cont
// 如果 head 和 tail 不存在，则追加在末尾
func SetManagedContent(orig, head, tail, cont []byte) []byte {
	var hh, _, _, tt = GetManagedIndexes(orig, head, tail)
	var result = make([]byte, len(cont)+len(orig)+len(head)+len(tail)+hh-tt)

	var offset = 0
	for _, p := range [][]byte{
		orig[:hh],
		head,
		cont,
		tail,
		orig[tt:],
	} {
		copy(result[offset:], p)
		offset += len(p)
	}

	return result
}

// GetManagedIndexes 返回索引
// hh 	Head 开始的位置
// ht	Head 结束的位置，即内容开始的位置
// th 	Tail 开始的位置，即内容结束的位置
// tt 	Tail 结束的位置
func GetManagedIndexes(orig, head, tail []byte) (hh, ht, th, tt int) {
	hh = bytes.Index(orig, head)
	if hh < 0 {
		th = bytes.Index(orig, tail)
		if th < 0 {
			th, tt = len(orig), len(orig)
		} else {
			tt = th + len(tail)
		}
		hh, ht = th, th
		return
	}

	ht = hh + len(head)

	th = bytes.Index(orig[ht:], tail)
	if th < 0 {
		th, tt = ht, ht
		return
	}
	th += ht
	tt = th + len(tail)

	return
}
