apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  namespace: {{ $.Values.namespace }}
  labels: {{- include "etcd.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: RequireDualStack
{{- end }}
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: client
      port: {{ .Values.service.port  }}
      targetPort: client
    - name: peer
      port: {{ .Values.service.peerPort  }}
      targetPort: peer
  selector: {{- include "etcd.matchLabels" . | nindent 4 }}
