apiVersion: v1
data:
  config: |
    version: v1
    flags:
      failOnInitError: false
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: {{ .Values.config.timeSlicing.replicas }}
kind: ConfigMap
metadata:
  name: nvidia-device-plugin
  namespace: {{ .Values.namespace }}

