apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      priorityClassName: "system-node-critical"
      serviceAccountName: nvidia-device-plugin
      shareProcessNamespace: true
      initContainers:
      - command: ["config-manager"]
        env:
        - name: ONESHOT
          value: "true"
        - name: KUBECONFIG
          value: ""
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: "spec.nodeName"
        - name: NODE_LABEL
          value: "nvidia.com/device-plugin.config"
        - name: CONFIG_FILE_SRCDIR
          value: "/available-configs"
        - name: CONFIG_FILE_DST
          value: "/config/config.yaml"
        - name: DEFAULT_CONFIG
          value: ""
        - name: FALLBACK_STRATEGIES
          value: "{{ join "," .Values.config.fallbackStrategies }}"
        - name: SEND_SIGNAL
          value: "false"
        - name: SIGNAL
          value: ""
        - name: PROCESS_TO_SIGNAL
          value: ""
        image: {{ .Values.image.registry }}/{{ .Values.image.NvidiaDevicePlugin.repository }}:{{ .Values.image.NvidiaDevicePlugin.tag }}
        imagePullPolicy: IfNotPresent
        name: nvidia-device-plugin-init
        volumeMounts:
        - mountPath: /available-configs
          name: available-configs
        - mountPath: /config
          name: config
      containers:
      - name: nvidia-device-plugin-sidecar
        image: {{ .Values.image.registry }}/{{ .Values.image.NvidiaDevicePlugin.repository }}:{{ .Values.image.NvidiaDevicePlugin.tag }}
        command: ["config-manager"]
        env:
        - name: ONESHOT
          value: "false"
        - name: KUBECONFIG
          value: ""
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: "spec.nodeName"
        - name: NODE_LABEL
          value: "nvidia.com/device-plugin.config"
        - name: CONFIG_FILE_SRCDIR
          value: "/available-configs"
        - name: CONFIG_FILE_DST
          value: "/config/config.yaml"
        - name: DEFAULT_CONFIG
          value: "{{ .Values.config.default }}"
        - name: FALLBACK_STRATEGIES
          value: "{{ join "," .Values.config.fallbackStrategies }}"
        - name: SEND_SIGNAL
          value: "true"
        - name: SIGNAL
          value: "1" # SIGHUP
        - name: PROCESS_TO_SIGNAL
          value: "nvidia-device-plugin"
        volumeMounts:
          - name: available-configs
            mountPath: /available-configs
          - name: config
            mountPath: /config
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      - image: {{ .Values.image.registry }}/{{ .Values.image.NvidiaDevicePlugin.repository }}:{{ .Values.image.NvidiaDevicePlugin.tag }}
        name: nvidia-device-plugin-ctr
        env:
        - name: CONFIG_FILE
          value: "/config/config.yaml"
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: available-configs
          mountPath: /available-configs
        - name: config
          mountPath: /config
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: available-configs
        configMap:
          defaultMode: 420
          name: nvidia-device-plugin
      - name: config
        emptyDir: {}
