# Default values for prometheus-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: "resource"

env:
  timezone: Asia/Shanghai

image:
  registry: acr.aishu.cn
  pullPolicy: IfNotPresent
  MongoShakeExporter:
    repository: proton/mongoshake-exporter
    tag: VERSION

service:
  port: 8000
  enableDualStack: false

config:
  mongoshakeurl: http://localhost:30040/repl
  scrapeInterval: 10

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 5m
    memory: 5Mi
