# permissions for end users to edit mongodboperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodboperator-editor-role
rules:
- apiGroups:
  - mongodb.proton.aishu.cn
  resources:
  - mongodboperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mongodb.proton.aishu.cn
  resources:
  - mongodboperators/status
  verbs:
  - get
