# permissions for end users to view mongodboperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodboperator-viewer-role
rules:
- apiGroups:
  - mongodb.proton.aishu.cn
  resources:
  - mongodboperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mongodb.proton.aishu.cn
  resources:
  - mongodboperators/status
  verbs:
  - get
