apiVersion: mongodb.proton.aishu.cn/v1
kind: MongodbOperator
metadata:
  name: mongodboperator
  namespace: default
  # namespace: mongodb
  # annotations: 
  #   "proton-mongodb-1.x-migrate": ""
spec:
  # TODO(user): Add fields here
  secretname: mongo-secret
  mongodb:
    replicas: 1
    replset:
      name: rs0
    image: acr.aishu.cn/proton/mongodb:2.0.0-develop
    imagePullPolicy: IfNotPresent
    service: 
      type: NodePort
      enableDualStack: false
      port: 30280
    debug: "0"
    conf:
      wiredTigerCacheSizeGB: 4
      tls:
        enabled: false
        # tlssecretname: ""
    storage:
      capacity: 10Gi
      storageClassName: ""
      volume:
        - host: node-10-10
          path: /sysvol/mongodb/mongodb-0
    resources:
      requests:
        cpu: 20m
        memory: 1Gi
  mgmt:
    image: acr.aishu.cn/proton/proton-mongodb-mgmt:2.1.0-develop
    imagePullPolicy: IfNotPresent
    service:
      type: NodePort
      enableDualStack: false
      port: 30281
    useEncryption: false
    logLevel: info
  exporter:
    image: acr.aishu.cn/proton/mongodb-exporter:2.1.0-develop
    imagePullPolicy: Always
  logrotate:
    image: acr.aishu.cn/proton/logrotate:1.0.1
    imagePullPolicy: IfNotPresent
    logsize: 2M
    schedule: "*/2 * * * *"
    logcount: 5