apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ .Values.namespace }}
data:
  datasource.yaml: |
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources:
      - name: VMetrics
        orgId: 1
      - name: VLogs
        orgId: 1

    # list of datasources to insert/update depending
    # whats available in the database
    datasources:
      # <string, required> name of the datasource. Required
    - name: VMetrics
      # <string, required> datasource type. Required
      type: prometheus
      # <string, required> access mode. direct or proxy. Required
      access: proxy
      # <int> org id. will default to orgId 1 if not specified
      orgId: 1
      # <string> url
      url: http://127.0.0.1:{{ .Values.config.vmetrics.port }}
      # <bool> mark as default datasource. Max one per org
      isDefault: true
      version: 1
      # <bool> allow users to edit datasources from the UI.
      editable: true
    
    - name: VLogs
      type: victoriametrics-logs-datasource
      access: proxy
      orgId: 1
      url: http://127.0.0.1:{{ .Values.config.vlogs.port }}
      isDefault: false
      version: 1
      editable: true
      jsonData:
        timeout: 120
        queryTimeout: 60
        maxLines: 10000
        httpMethod: GET
      

