{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "configuration-management.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "configuration-management.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "configuration-management.serviceAccountName" . }}-cluster-role-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "configuration-management.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ template "configuration-management.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "configuration-management.serviceAccountName" . }}-cluster-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - '*'
    verbs:
      - "*"
{{- end -}}
