package node

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"net"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/lithammer/dedent"
	"github.com/sirupsen/logrus"

	"devops.aishu.cn/AISHUDevOps/ICT/_git/proton-opensource.git/proton-cli/v3/pkg/client/ecms/v1alpha1/files"
	exec "devops.aishu.cn/AISHUDevOps/ICT/_git/proton-opensource.git/proton-cli/v3/pkg/client/exec/v1alpha1"
	"devops.aishu.cn/AISHUDevOps/ICT/_git/proton-opensource.git/proton-cli/v3/util/file"
)

const (
	// Chrony 配置文件
	ChronyConfigPath = "/etc/chrony.conf"
	// Chrony 配置文件目录
	ChronyConfigDirectory = "/etc/chrony.d"
	// Proton 提供的 chrony 配置文件名称
	ChronyConfigProtonFilename = "00-proton.conf"
	// Chrony 配置文件中受 Proton 管理的标志符
	headFlag, tailFlag = file.ProtonCLIAutoGeneratedHeadFlag, file.ProtonCLIAutoGeneratedTailFlag
)

// 更新节点 chrony 配置，包括持久化配置文件和运行时配置
func (n *Node) UpdateChronyConfig(logger logrus.FieldLogger, e exec.Executor, f files.Interface, servers []string) error {
	var ctx = context.TODO()
	if err := n.UpdateChronyConfigFile(logger, f); err != nil {
		return fmt.Errorf("update chrony config file fail: %w", err)
	}

	if _, err := f.Stat(ctx, ChronyConfigDirectory); errors.Is(err, fs.ErrNotExist) {
		logger.WithField("path", ChronyConfigDirectory).Info("create chrony config directory")
		if err := f.Create(ctx, ChronyConfigDirectory, true, nil); err != nil {
			return err
		}
	} else if err != nil {
		return err
	}

	if err := n.UpdateChronyConfigProtonFile(logger, f, servers); err != nil {
		return fmt.Errorf("update chrony config proton file fail: %w", err)
	}

	// 如果 chronyd 未运行则启动，启动后不需要再修改运行时配置
	if isActive, err := n.systemctlIsActiveChronyd(e); err != nil {
		return err
	} else if !isActive {
		logger.Info("start chronyd")
		return e.Command("systemctl", "start", "chronyd").Run()
	}

	// 修改运行时配置
	// 	1. 作为 ntp source 允许 ntp 客户端访问
	// 	2. 即使未与上游 ntp source 同步，也作为 ntp source 提供服务
	// 	3. 获取时间源
	//  4. 添加缺少的时间源
	if err := n.updateChronyRuntimeConfig(logger, e, servers); err != nil {
		return err
	}

	return nil
}

// 更新 chrony 配置文件，添加 include 字段包括 proton 提供的 chrony 配置文件
func (n *Node) UpdateChronyConfigFile(logger logrus.FieldLogger, f files.Interface) error {
	var ctx = context.TODO()

	origin, err := f.ReadFile(ctx, ChronyConfigPath)
	if err != nil {
		return err
	}

	// 注释掉所有以server和pool开头的行，执行到这里证明已经是使用内置或外置时间服务器中的一种选项了，如果是用户手动管理的话这个函数根本不会被执行
	originCommentExistingServers := commentAllServerPool(origin)

	actual := file.GetManagedContent(origin, []byte(headFlag), []byte(tailFlag))
	expect := []byte(fmt.Sprintf("include %s\n", filepath.Join(ChronyConfigDirectory, ChronyConfigProtonFilename)))
	// 如果include部分一致且所有现有时间服务器已经被注释，就直接返回
	if bytes.Equal(actual, expect) && bytes.Equal(origin, originCommentExistingServers) {
		logger.Debug("The chrony config file already exists and updated")
		return nil
	}

	return f.Create(ctx, ChronyConfigPath, false, file.SetManagedContent(originCommentExistingServers, []byte(headFlag), []byte(tailFlag), expect))
}

func commentAllServerPool(origin []byte) []byte {
	var output string
	scanner := bufio.NewScanner(bytes.NewReader(origin))
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "server") || strings.HasPrefix(line, "pool") {
			line = "#" + line
		}
		output = output + line + "\n"
	}
	// 分析原始内容是否有回车，以决定结尾是否包含回车
	if !strings.HasSuffix(string(origin), "\n") {
		output = strings.TrimSuffix(output, "\n")
	}
	return []byte(output)
}

// 给chrony服务器用的配置文件模板，适用于使用内置服务器时被选中的master节点，只作为服务器不作为客户端，意味着其自身的时间不能被chrony调整
var ChronyPConfigTemplateServer = dedent.Dedent(`
	# Allow NTP client access from local network.
	allow 0/0

	# Serve time even if not synchronized to any NTP server.
	local stratum 10 orphan
`)

// 给chrony客户端用的配置文件模板，适用于使用外置服务器的场景和使用内置服务器除被选中的master之外的节点，只作为客户端不作为服务器
var ChronyPConfigTemplateClient = template.Must(template.New("proton-chrony-config-client").Parse(dedent.Dedent(`
	# Enable kernel RTC synchronization.
	rtcsync

	# Servers
	{{ range $server := . -}}
	server {{ $server }} iburst
	{{ end -}}
`)))

// 更新 Proton 提供的 chrony 配置文件
// 此处认为servers数组为空意味着该节点为被选中提供NTP时间同步的master节点，否则不为空意味着这是客户端节点，只与servers中的服务器同步而不对外提供服务
func (n *Node) UpdateChronyConfigProtonFile(logger logrus.FieldLogger, f files.Interface, servers []string) error {
	var ctx = context.TODO()
	expect := new(bytes.Buffer)
	if len(servers) == 0 {
		// servers长度为0，视为服务器，只对外提供时间服务，自身的时间无法被调整
		if _, err := expect.WriteString(ChronyPConfigTemplateServer); err != nil {
			return err
		}
	} else {
		// 否则为客户端，通过servers数组中的服务器调整时间，自身不提供时间服务
		if err := ChronyPConfigTemplateClient.Execute(expect, servers); err != nil {
			return err
		}
	}

	path := filepath.Join(ChronyConfigDirectory, ChronyConfigProtonFilename)

	actual, err := f.ReadFile(ctx, path)
	if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	if bytes.Equal(actual, expect.Bytes()) {
		logger.Debug("The chrony config proton file already exists and is updated")
		return nil
	}

	logger.Info("Update chrony config proton file")
	return f.Create(ctx, path, false, expect.Bytes())
}

func (n *Node) systemctlIsActiveChronyd(e exec.Executor) (bool, error) {
	err := e.Command("systemctl", "is-active", "chronyd").Run()
	if err == nil {
		return true, nil
	}
	// systemctl status code 3 means "program is not running"
	if ee := new(exec.ErrExitError); errors.As(err, &ee) && ee.ExitCode == 3 {
		return false, nil
	}
	return false, err
}

// updateChronyRuntimeConfig 通过命令 chronyc 更新 chrony 的运行时配置
//
//  1. 作为 ntp source 允许 ntp 客户端访问
//  2. 即使未与上游 ntp source 同步，也作为 ntp source 提供服务
//  3. 获取时间源
//  4. 添加缺少的时间源
func (n *Node) updateChronyRuntimeConfig(logger logrus.FieldLogger, e exec.Executor, servers []string) error {
	// 不管采用何种方式，都需要删除所有现有时间源
	sources, err := n.chronycSources(e)
	if err != nil {
		return err
	}
	for _, origsrc := range sources {
		if err := e.Command("chronyc", "delete", origsrc).Run(); err != nil {
			return err
		}
	}

	if len(servers) == 0 {
		logger.Info("allow ntp clients to access")
		if err := e.Command("chronyc", "allow", "0/0").Run(); err != nil {
			return err
		}
		logger.Info("enable chrony local reference mode")
		if err := e.Command("chronyc", "local", "orphan").Run(); err != nil {
			return err
		}
	} else {
		// 由于已经删除了所有现有时间源，直接把servers里的都添加上即可
		for _, s := range servers {
			logger.WithField("source", s).Info("add chrony source")
			if err := e.Command("chronyc", "add", "server", s).Run(); err != nil {
				return err
			}
		}
	}

	return nil
}

// parseChronycSourcesOutput 解析命令 `chronyc sources` 的输出，返回时间源的 ip 地址列表
func parseChronycSourcesOutput(output []byte) ([]string, error) {
	scanner := bufio.NewScanner(bytes.NewReader(output))

	var ips []string

	var skippedHeader bool
	var lineN int
	for scanner.Scan() {
		line := scanner.Text()
		lineN++
		if len(line) == strings.Count(line, "=") {
			skippedHeader = true
			continue
		}
		if !skippedHeader {
			continue
		}

		fields := strings.Fields(line)
		if len(fields) < 2 {
			return nil, fmt.Errorf("less than 2 fields, line %d: %q", lineN, line)
		}
		ip := net.ParseIP(fields[1])
		if ip == nil {
			return nil, fmt.Errorf("in valid ip address, line %d: %q", lineN, line)
		}

		ips = append(ips, ip.String())
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return ips, nil
}

// chronycSources 通过 ssh 远程调用命令 chronyc sources 获取已配置的时间源
func (n *Node) chronycSources(e exec.Executor) ([]string, error) {
	// 时间源使用 IP 配置，所以使用参数 `-n` 返回 ip 地址而非主机名
	out, err := e.Command("chronyc", "-n", "sources").Output()
	if err != nil {
		return nil, err
	}
	return parseChronycSourcesOutput(out)
}
