{
 "title": "Kubernetes Pods Dashboard",
 "tags": [
  "kubernetes",
  "pods",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Metrics Datasource", "query": "prometheus" },
   {
    "name": "logsDatasource",
    "label": "Logs Datasource",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", created_by_kind!=\"Job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods in Namespace: $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\", created_by_kind!=\"Job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\"}) by (pod) /1024 /1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process IO Read rate[1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_process_io{container=\"$pod\", metric=\"read_bytes\"}[1m])",
     "legendFormat": "{{container}}: {{process}}"
    }
   ]
  },
  {
   "title": "Process IO Write rate[1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_process_io{container=\"$pod\", metric=\"write_bytes\"}[1m])",
     "legendFormat": "{{container}}: {{process}}"
    }
   ]
  },
  {
   "title": "Memory Usage: $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "TCP ESTAB Conns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_tcp_connection{container_name=\"$pod\", state=\"established\"}",
     "legendFormat": "{{container_name}}->{{dest_ip}}:{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usage: $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network Traffic: $pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[5m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Pod Logs: $pod",
   "type": "logs",
   "description": "Logs for the selected pod",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "kubernetes.namespace_name:$namespace and  kubernetes.pod_name:$pod"
    }
   ]
  }
 ]
}