{
 "title": "K8S_Apiserver",
 "tags": [
  "product",
  "kubernetes",
  "anyrobot",
  "monitor",
  "apiserver"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})",
     "legendFormat": "点击查看Pods"
    }
   ]
  },
  {
   "title": "请求速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Etcd请求延迟",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "请求延迟",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  },
  {
   "title": "工作队列处理时间",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "工作队列服务时间",
   "type": "timeseries",
   "description": "P99：当前时间点99%的指标值都小于当前值\n\nP90：当前时间点90%的指标值都小于当前值\n\nP50：当前时间点50%的指标值都小于当前值",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "apiserver logs",
   "type": "logs",
   "description": "apiserver logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kubernetes.container_name:\"kube-apiserver\""
    }
   ]
  }
 ]
}