{
 "title": "MongoDB",
 "description": "MongoDB Prometheus Exporter Dashboard. A fork inspired from https://grafana.com/grafana/dashboards/2583 which is made to work well with https://github.com/percona/mongodb_exporter.",
 "tags": [ "prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "podname",
    "label": "podname",
    "query": {
     "query": "label_values(mongodb_ss_connections,name)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(mongodb_members_health,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod,node,pod_ip)"
    },
    {
     "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "运行时长"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "重启次数"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "容器数"
    },
    {
     "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod,phase))>0",
     "legendFormat": "状态"
    },
    {
     "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "副本状态"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "请求内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$podname\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "使用内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "请求CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$podname\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$podname\"}[$__range]))by(pod)",
     "legendFormat": "重启次数(当前字段)"
    }
   ]
  },
  {
   "title": "Query Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_oplog_stats_count{name=~\"$podname\"}[$interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{name=~\"$podname\"}[$interval])",
     "legendFormat": "{{name}}-{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "AppliedWallTime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(mongodb_optimes_lastAppliedWallTime{rs_state=\"1\"}) - mongodb_optimes_lastAppliedWallTime{rs_state=\"2\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Member State",
   "type": "stat",
   "description": "See which node is currently acting as the primary, secondary, ...",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(member_idx) (mongodb_rs_members_health{app=\"mongodb-mongodb\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{name=~\"$podname\",conn_type=\"active\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{name=~\"$podname\",conn_type=\"available\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "zookeeper related logs",
   "type": "logs",
   "description": "kafka logs",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kubernetes.namespace_name:$namespace and kubernetes.container_name:\"mongodb\""
    }
   ]
  }
 ]
}