{
 "title": "OpenSearch",
 "description": "DIsplay OpenSearch key metrics from Prometheus",
 "tags": [
  "product",
  "opensearch",
  "app",
  "monitor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "时间间隔", "query": "5m" },
   {
    "name": "cluster",
    "label": "集群",
    "query": {
     "query": "label_values(opensearch_cluster_health_status, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "命名空间",
    "query": {
     "query": "label_values(opensearch_cluster_health_status{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "name",
    "label": "容器节点",
    "query": {
     "query": "label_values(opensearch_jvm_memory_max_bytes{cluster=\"$cluster\"}, name)"
    }
   },
   { "name": "datasource", "label": "Metrics Datasource", "query": "prometheus" },
   {
    "name": "logsDatasource",
    "label": "Logs Datasource",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群状态",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(opensearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1)-1",
     "legendFormat": "{{cluster}}"
    },
    {
     "expr": "opensearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1",
     "legendFormat": "{{cluster}}"
    },
    {
     "expr": "(opensearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1)+1",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "集群状态(柱状图)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opensearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"} == 1",
     "legendFormat": "GREEN"
    },
    {
     "expr": "opensearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"} == 1",
     "legendFormat": "YELLOW"
    },
    {
     "expr": "opensearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"} == 1",
     "legendFormat": "RED"
    }
   ]
  },
  {
   "title": "节点数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{statefulset=~\"$cluster.*\"})",
     "legendFormat": "总数"
    },
    {
     "expr": "opensearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}",
     "legendFormat": "当前总数"
    },
    {
     "expr": "opensearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}",
     "legendFormat": "当前数据节点"
    }
   ]
  },
  {
   "title": "索引数 & 段数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_indices_total{cluster=\"$cluster\"}",
     "legendFormat": "索引数"
    },
    {
     "expr": "sum(opensearch_indices_segments_count{cluster=\"$cluster\"})",
     "legendFormat": "段数"
    }
   ]
  },
  {
   "title": "分片数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_health_active_shards{cluster=\"$cluster\"}",
     "legendFormat": "活跃"
    },
    {
     "expr": "opensearch_cluster_health_initializing_shards{cluster=\"$cluster\"}",
     "legendFormat": "初始化"
    },
    {
     "expr": "opensearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}",
     "legendFormat": "活跃主分片"
    },
    {
     "expr": "opensearch_cluster_health_relocating_shards{cluster=\"$cluster\"}",
     "legendFormat": "重定位"
    },
    {
     "expr": "opensearch_cluster_health_unassigned_shards{cluster=\"$cluster\"}",
     "legendFormat": "未分配"
    },
    {
     "expr": "opensearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"}",
     "legendFormat": "延迟分配"
    }
   ]
  },
  {
   "title": "数据速率",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(opensearch_indices_indexing_index_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "索引"
    },
    {
     "expr": "sum(irate(opensearch_indices_search_fetch_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": " 获取"
    },
    {
     "expr": "sum(irate(opensearch_indices_search_query_total{cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "查询"
    }
   ]
  },
  {
   "title": "JVM堆内存使用率",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(opensearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"heap\"})/sum(opensearch_jvm_memory_max_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"heap\"}))",
     "legendFormat": "JVM内存使用率"
    }
   ]
  },
  {
   "title": "JVM堆内存",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"heap\"})",
     "legendFormat": "已使用空间"
    },
    {
     "expr": "sum(opensearch_jvm_memory_max_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"heap\"})",
     "legendFormat": "总空间"
    }
   ]
  },
  {
   "title": "磁盘利用率(总计)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((sum(opensearch_filesystem_data_size_bytes{cluster=\"$cluster\"})-sum(opensearch_filesystem_data_free_bytes{cluster=\"$cluster\"}))/sum(opensearch_filesystem_data_size_bytes{cluster=\"$cluster\"}))",
     "legendFormat": "磁盘利用率"
    }
   ]
  },
  {
   "title": "磁盘空间",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(opensearch_filesystem_data_size_bytes{cluster=\"$cluster\"})-sum(opensearch_filesystem_data_free_bytes{cluster=\"$cluster\"}))",
     "legendFormat": "已使用"
    },
    {
     "expr": "sum(opensearch_filesystem_data_size_bytes{cluster=\"$cluster\"})",
     "legendFormat": "总空间"
    }
   ]
  },
  {
   "title": "待分配任务数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_cluster_health_number_of_pending_tasks{cluster=~\"$cluster\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "索引 & 查询 & 获取",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "索引增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "索引速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(opensearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "搜索平均速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$name\"})/sum(opensearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$name\"})",
       "legendFormat": "搜索平均速率"
      }
     ]
    },
    {
     "title": "查询获取速率差",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(opensearch_indices_search_fetch_time_seconds{cluster=\"$cluster\", name=~\"$name\"}/opensearch_indices_search_fetch_total{cluster=\"$cluster\", name=~\"$name\"})-(opensearch_indices_search_query_time_seconds{cluster=\"$cluster\", name=~\"$name\"}/opensearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询 & 获取增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_search_fetch_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 获取"
      },
      {
       "expr": "sum(irate(opensearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 查询"
      }
     ]
    },
    {
     "title": "查询 & 获取速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(opensearch_indices_search_fetch_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 获取"
      },
      {
       "expr": "sum(rate(opensearch_indices_search_query_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 查询"
      }
     ]
    },
    {
     "title": "索引延迟",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]) / irate(opensearch_indices_indexing_index_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询 & 获取延迟",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_search_query_time_seconds{cluster=\"opensearch\", name=~\"$name\"}[$interval]) / irate(opensearch_indices_search_query_total{cluster=\"opensearch\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 查询"
      },
      {
       "expr": "sum(irate(opensearch_indices_search_fetch_time_seconds{cluster=\"opensearch\", name=~\"$name\"}[$interval]) / irate(opensearch_indices_search_fetch_total{cluster=\"opensearch\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: 获取"
      }
     ]
    },
    {
     "title": "段数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_segments_count{cluster=\"$cluster\",name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}: 段数"
      }
     ]
    },
    {
     "title": "索引数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_indices_total{cluster=\"$cluster\"}",
       "legendFormat": "索引数"
      }
     ]
    },
    {
     "title": "Refresh & Flush 延迟",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_refresh_time_seconds_total{cluster=\"opensearch\", name=~\"$name\"}[$interval]) / irate(opensearch_indices_refresh_total{cluster=\"opensearch\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: Refresh"
      },
      {
       "expr": "sum(irate(opensearch_indices_flush_time_seconds{cluster=\"$cluster\", name=~\"$name\"}[$interval]) / irate(opensearch_indices_flush_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: Flush"
      }
     ]
    }
   ]
  },
  {
   "title": "分片 & 文档",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "活跃分片数(总数和主分片数)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_active_shards{cluster=\"$cluster\"}",
       "legendFormat": "活跃分片数"
      },
      {
       "expr": "opensearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}",
       "legendFormat": "活跃主分片数"
      }
     ]
    },
    {
     "title": "分片数(初始化、重定位、未分配、延时分配)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_initializing_shards{cluster=\"$cluster\"}",
       "legendFormat": "初始化分片数"
      },
      {
       "expr": "opensearch_cluster_health_relocating_shards{cluster=\"$cluster\"}",
       "legendFormat": "重定位分片数"
      },
      {
       "expr": "opensearch_cluster_health_unassigned_shards{cluster=\"$cluster\"}",
       "legendFormat": "未分配分片数"
      },
      {
       "expr": "opensearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"}",
       "legendFormat": "延时分配分片数"
      }
     ]
    },
    {
     "title": "文档数（含副本）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_docs{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "文档合并增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_merges_docs_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "文档删除速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "count(irate(opensearch_indices_docs_deleted{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "当前合并数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_merges_current{cluster=\"$cluster\", name=~\"$name\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "段数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_segments_count{cluster=\"$cluster\", name=~\"$name\"}) by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "线程池",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "队列数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_thread_pool_queue_count{cluster=~\"$cluster\", name=~\"$name\", type!=\"management\"}) by (type)",
       "legendFormat": "Type: {{type}}"
      }
     ]
    },
    {
     "title": "写入线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"write\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "Flush线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"flush\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "搜索线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"search\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "Refresh线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"refresh\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "通用线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"generic\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "管理线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"management\"}[$interval]))by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "强制合并线程池增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: active"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: rejected"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: completed"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: largest"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: queue"
      },
      {
       "expr": "sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\", type=\"force_merge\"}[$interval])) by(name)",
       "legendFormat": "{{name}}: size"
      }
     ]
    },
    {
     "title": "线程池增长速率(总计前五)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "topk(5, sum(irate(opensearch_thread_pool_threads_count{cluster=\"$cluster\", name=~\"$name\"}[$interval])) by(type, name))",
       "legendFormat": "{{name}}-{{type}}: size"
      },
      {
       "expr": "topk(5,sum(irate(opensearch_thread_pool_active_count{cluster=\"$cluster\", name=~\"$name\"}[$interval])) by(type, name))",
       "legendFormat": "{{name}}-{{type}}: active"
      },
      {
       "expr": "topk(5, sum(irate(opensearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(type,name))",
       "legendFormat": "{{name}}-{{type}}: reject"
      },
      {
       "expr": "topk(5, sum(irate(opensearch_thread_pool_completed_count{cluster=\"$cluster\", name=~\"$name\"}[$interval])) by(type, name))",
       "legendFormat": "{{name}}-{{type}}: completed"
      },
      {
       "expr": "topk(5,sum(irate(opensearch_thread_pool_largest_count{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(type,name))",
       "legendFormat": "{{name}}-{{type}}: largest"
      },
      {
       "expr": "topk(5,sum(irate(opensearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(type,name))",
       "legendFormat": "{{name}}-{{type}}: queue"
      }
     ]
    }
   ]
  },
  {
   "title": "缓存",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "查询缓存数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_query_cache_count{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_indices_query_cache_cache_size{cluster=\"$cluster\", name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存命中数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_query_cache_count{cluster=\"$cluster\", name=~\"$name\",cache=\"hit\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存命中率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_query_cache_count{cluster=\"$cluster\", name=~\"$name\",cache=\"hit\"})by(name)/(sum(opensearch_indices_query_cache_count{cluster=\"$cluster\", name=~\"$name\",cache=\"hit\"})by(name) + sum(opensearch_indices_query_miss_count{cluster=\"$cluster\", name=~\"$name\",cache=\"miss\"})by(name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存丢失数增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_query_miss_count{cluster=\"$cluster\", name=~\"$name\",cache=\"miss\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存分配内存大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_query_cache_memory_size_bytes{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "字段数据分配内存大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "查询缓存驱逐数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "opensearch_indices_query_cache_evictions{cluster=\"$cluster\", name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "字段数据占用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",name=~\"$name\"})by(name)/sum(opensearch_jvm_memory_committed_bytes{cluster=\"$cluster\",name=~\"$name\",area=~\"heap\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "字段数据驱逐数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_fielddata_evictions{cluster=\"$cluster\", name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "请求缓存驱逐数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "opensearch_indices_request_cache_evictions{cluster=\"$cluster\", name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "请求缓存数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_request_cache_count{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "请求缓存分配内存大小",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_indices_request_cache_memory_size_bytes{cluster=\"$cluster\", name=~\"$name\"})by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "请求缓存丢失数增长速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(opensearch_indices_request_miss_count{cluster=\"$cluster\", name=~\"$name\",cache=\"miss\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "限流 & 待执行任务",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "索引限流率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_indexing_throttle_time_seconds_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "合并限流率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_indices_merges_total_throttled_time_seconds_total{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "待执行任务数",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 204 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"}",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "系统",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "磁盘使用情况",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})by(name)",
       "legendFormat": "总空间"
      },
      {
       "expr": "sum(opensearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"})by(name)",
       "legendFormat": "可用空间"
      },
      {
       "expr": "sum(1 - opensearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"} / opensearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})by(name)",
       "legendFormat": "使用率"
      }
     ]
    },
    {
     "title": "磁盘占用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(1 - opensearch_filesystem_data_available_bytes{cluster=\"$cluster\",name=~\"$name\"} / opensearch_filesystem_data_size_bytes{cluster=\"$cluster\",name=~\"$name\"})by(name,path)",
       "legendFormat": "{{name}} - {{path}}"
      }
     ]
    },
    {
     "title": "打开文件描述符数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "opensearch_process_open_files_count{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}-当前"
      },
      {
       "expr": "opensearch_process_max_files_descriptors{cluster=\"$cluster\",name=~\"$name\"}",
       "legendFormat": "{{name}}-最大"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC 速率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval]))by(name,gc)",
       "legendFormat": "{{name}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC 耗时增长率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(irate(opensearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\", name=~\"$name\"}[$interval]))by(name,gc)",
       "legendFormat": "{{name}}: {{gc}}"
      }
     ]
    },
    {
     "title": "Full GC 次数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(opensearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\",gc=\"old\"})by(name,gc)",
       "legendFormat": "{{name}}: {{gc}}"
      }
     ]
    },
    {
     "title": "GC 平均耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(opensearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[$interval]))by(name,gc)",
       "legendFormat": "{{name}}: {{gc}}"
      }
     ]
    },
    {
     "title": "堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$name\",area=\"heap\"})by(name)",
       "legendFormat": "{{name}}: 已使用"
      },
      {
       "expr": "sum(opensearch_jvm_memory_committed_bytes{cluster=\"$cluster\", name=~\"$name\",area=\"heap\"})by(name)",
       "legendFormat": "{{name}}: 已提交"
      }
     ]
    },
    {
     "title": "非堆内存(已使用、已提交)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(opensearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"non-heap\"})by(name)",
       "legendFormat": "{{name}}: 已使用"
      },
      {
       "expr": "sum(opensearch_jvm_memory_committed_bytes{cluster=\"$cluster\", name=~\"$name\", area=\"non-heap\"})by(name)",
       "legendFormat": "{{name}}: 已提交"
      }
     ]
    },
    {
     "title": "堆平均使用率(15m)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time(opensearch_jvm_memory_used_bytes{area=\"heap\",name=~\"$name\",cluster=~\"$cluster\"}[15m]) / opensearch_jvm_memory_max_bytes{area=\"heap\",name=~\"$name\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "堆使用率",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100*(sum(opensearch_jvm_memory_used_bytes{cluster=\"$cluster\", name=~\"$name\",area=\"heap\"})by(name)/sum(opensearch_jvm_memory_max_bytes{cluster=\"$cluster\", name=~\"$name\",area=\"heap\"})by(name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\",container!=\"POD\"})by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "CPU使用情况",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "Cores" } },
     "targets": [
      {
       "expr": "sum ( irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$name\"}[5m])) by(pod) ",
       "legendFormat": "{{pod}}: 使用数"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 请求数"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) ",
       "legendFormat": "{{pod}}: 限制数"
      }
     ]
    },
    {
     "title": "网络流量",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$name\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流入"
      },
      {
       "expr": "sort_desc(sum by (pod) (irate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$name\"}[5m]) ))",
       "legendFormat": "{{pod}}: 流出"
      }
     ]
    },
    {
     "title": "磁盘读写速率",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 199 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum (irate(container_fs_reads_bytes_total{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 读取-{{ device }}"
      },
      {
       "expr": "sum (irate(container_fs_writes_bytes_total{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\", container!=\"POD\"}[5m]))by(pod,device) ",
       "legendFormat": "{{pod}}: 写入- {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod列表",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod,node,pod_ip)"
      },
      {
       "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$name\"})by(pod)",
       "legendFormat": "运行时长"
      },
      {
       "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$name\"})by(pod)",
       "legendFormat": "重启次数"
      },
      {
       "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod)",
       "legendFormat": "容器数"
      },
      {
       "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$name\"})by(pod,phase))>0",
       "legendFormat": "状态"
      },
      {
       "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$name\"})by(pod))",
       "legendFormat": "副本状态"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "请求内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "限制内存"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$name\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "使用内存"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "请求CPU"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$name\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$name\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$name\"})by(pod))",
       "legendFormat": "限制CPU"
      },
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$name\"}[$__range]))by(pod)",
       "legendFormat": "重启次数(当前时段)"
      }
     ]
    },
    {
     "title": "logs",
     "type": "logs",
     "description": "kafka logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "kubernetes.namespace_name:$namespace and kubernetes.container_name:\"opensearch\""
      }
     ]
    }
   ]
  }
 ]
}