{
 "title": "Redis",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(redis_cluster_enabled,namespace)"
    }
   },
   {
    "name": "podname",
    "label": "podname",
    "query": {
     "query": "label_values(redis_cluster_enabled,pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod列表",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod,node,pod_ip)"
    },
    {
     "expr": "time() - sum(kube_pod_created{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "运行时长"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "重启次数"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod)",
     "legendFormat": "容器数"
    },
    {
     "expr": "(sum(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod,phase))>0",
     "legendFormat": "状态"
    },
    {
     "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",condition=\"true\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "副本状态"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "请求内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"memory\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=~\"$namespace\",image!=\"\", pod=~\"$podname\",container!=\"POD\"})by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "使用内存"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "请求CPU"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$podname\", resource=\"cpu\"}) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum ( rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",pod=~\"$podname\"}[5m])) by(pod) or (sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod) - sum(kube_pod_info{namespace=~\"$namespace\",pod=~\"$podname\"})by(pod))",
     "legendFormat": "限制CPU"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$podname\"}[$__range]))by(pod)",
     "legendFormat": "重启次数(当前字段)"
    }
   ]
  },
  {
   "title": "SyncStreamOffset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(redis_master_repl_offset{app=\"proton-redis-proton-redis\"}) - redis_slave_repl_offset{app=\"proton-redis-proton-redis\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "RejectConnections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_rejected_connections_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "InputNetwork",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OutNetwork",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redis_net_output_bytes_total[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CommandProcessTotal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "redis_commands_processed_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "RedisMemoryLimit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_max_bytes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "RedisMemoryUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}