FROM acr.aishu.cn/proton/nginx-ingress-controller:v1.3.1-1 AS controller
FROM acr.aishu.cn/proton/nginx-ingress-controller:0.32.0 AS controller118
FROM acr.aishu.cn/proton/nginx-ingress-controller:v1.12.3-1 AS controller120
FROM acr.aishu.cn/public/ubuntu:22.04.20251014 AS runtime