{{- $ins := index .Values.depServices "deploy-installer" }}
{{- $cor := index .Values.depServices "deploy-core" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "deploy-installer.name" . }}
  namespace: {{ template "deploy-installer.namespace" . }}
stringData:
  config.yaml: |
    protonConf:
      namespace: {{ $ins.protonConf.namespace }}
    rds:
      dbName: {{ $cor.database }}
    parallel: {{ $ins.parallel}}
    system:
      systemName: {{ $ins.system_name}}
      namespace: {{ template "deploy-installer.namespace" . }}
