apiVersion: v1
kind: Service
metadata:
  name: {{ template "deploy-installer.name" . }}
  namespace: {{ template "deploy-installer.namespace" . }}
  labels:
    {{- include "deploy-installer.labels" . | nindent 4 }}
spec:
{{- if .Values.service.enableDualStack }}
  ipFamilies:
  - IPv6
  - IPv4
  ipFamilyPolicy: PreferDualStack
{{- end }}
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    {{ include "deploy-installer.labels" . | nindent 4 }}