{{- if .Values.storage.repo.hdfs.enabled }}
{{- if (eq .Values.config.nodeGroup "master") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.clusterName }}-secret-krb5
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "opensearch.name" . }}
    cluster: {{ .Values.config.clusterName }}
type: Opaque
data:
  krb5.keytab: |-
    {{ .Files.Get "krb5/krb5.keytab" | b64enc }}
  krb5.conf: |-
    {{ .Files.Get "krb5/krb5.conf" | b64enc }}
{{- end }}
{{- end }}