{{- if (eq .Values.config.nodeGroup "master") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.clusterName }}-exporter-auth
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "opensearch.name" . }}
    cluster: {{ .Values.config.clusterName }}
type: kubernetes.io/basic-auth
data:
  username: {{ "exporter" | b64enc }}
  password: {{ .Values.config.exporterPassword | default "" | b64enc }}
{{- end }}
