package configlib

import (
	"reflect"
	"strings"
	"testing"
	"unicode"

	"github.com/go-test/deep"
)

func TestConvertMapToStr(t *testing.T) {
	cases := []struct {
		input map[string]string
	}{
		{
			input: map[string]string{
				"DEVICE":    "eth0",
				"BOOTPROTO": "static",
			}},
	}

	for _, c := range cases {
		got := make(map[string]string)
		for _, l := range strings.Fields(ConvertMapToStr(c.input)) {
			kv := strings.FieldsFunc(l, func(r rune) bool { return r == '=' || unicode.IsSpace(r) })
			if len(kv) != 2 {
				t.Errorf("invalid line: %q", l)
				continue
			}
			got[kv[0]] = kv[1]
		}
		for _, diff := range deep.Equal(got, c.input) {
			t.Errorf("ConvertMapToStr() got vs want: %v", diff)
		}
	}
}

func TestConvertStrToMap(t *testing.T) {
	type args struct {
		str string
	}
	tests := []struct {
		name string
		args args
		want map[string]string
	}{
		{
			name: "",
			args: args{
				str: `# Generated by VMWare customization engine.
				DEVICE=eth0
				BOOTPROTO=static`,
			},
			want: map[string]string{
				"DEVICE":    "eth0",
				"BOOTPROTO": "static"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := ConvertStrToMap(tt.args.str)
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("ConvertStrToMap() = %v, want %v", got, tt.want)
			}
		})
	}
}
